server:
  port: 8888
  
spring:
  application:
    name: spring-cloud-config-server
  cloud:    config:      server:        git:          uri: file:///E:\Cognizant\Project\configuration\git-localconfig-repo  
    